#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-SVG
version:      0.19
version_from: SVG.pm
installdirs:  site
requires:
    SVG:                           0
    GD:                            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
